### ISSUE TITLE
sparql queries during load/commit process should use the update url

### ISSUE THREAD

**Issue by dlamoris** [Open-MBEE/mms5-layer1-service#111]
There's been occasionally some model loads that results in a transaction failed error, but trying again works fine. I suspect this has to do with the queries during the load process that checks for the transaction and didn't find it. This can happen if the sparql updates are going to the db writer but queries are going to the reader, and there's enough lag in replication from writer to reader. 

To prevent it, any queries made as part of the commit/load process should use the update url instead of the query url to ensure it's always getting the latest data. (this applies to db cluster that have a writer and 1 or more readers)

**Comment by blake-regalia** [comment]
https://github.com/Open-MBEE/mms5-layer1-service/blob/develop/src/main/kotlin/org/openmbee/mms5/MmsL1.kt#L607

In create, update and delete routes, the `executeSparqlQuery` function is being called which queries read-only endpoint but should only and always query the writer endpoint
