### ISSUE TITLE
ability to create group with namespace

### ISSUE THREAD

**Issue by dlamoris** [Open-MBEE/mms5-layer1-service#118]
current group create returns a 404 if given this
ex. put /groups/namespace/blah/blah
expected behavior is to create group with id 'namespace/blah/blah'

also the created group iri without namespace (ex. put /groups/blah) is <context/group/blah>, should be <context/groups/blah>

**Comment by dlamoris** [comment]
first issue solved by escaping (use /groups/namespace%2Fblah%2Fblah)

**Comment by blake-regalia** [comment]
Fixed in https://github.com/Open-MBEE/mms5-layer1-service/commit/f9abdfe9de153e6afd57bedcdb25364140ec55e0
