### ISSUE TITLE
configurable http client request timeout

### ISSUE THREAD

**Issue by dlamoris** [Open-MBEE/mms5-layer1-service#120]
on model load if the load request exceeds the client request timeout no error is logged

need to
1. make sparql client request timeout configurable (or infinite?) https://github.com/Open-MBEE/mms5-layer1-service/blob/develop/src/main/kotlin/org/openmbee/mms5/plugins/Routing.kt#L25 
2. log error if timeout occurs https://github.com/Open-MBEE/mms5-layer1-service/blob/develop/src/main/kotlin/org/openmbee/mms5/routes/gsp/ModelLoad.kt#L139C32-L139C32

**Comment by blake-regalia** [comment]
If the client times out it will throw an exception which _should_ get caught by Ktor and handled as a 500, so (2) should already be handled
