### ISSUE TITLE
snapshot should point to a commit, ensure no dangling refs

### ISSUE THREAD

**Issue by blake-regalia** [Open-MBEE/mms5-layer1-service#84]

**Comment by blake-regalia** [comment]
Review ontology, snapshot should point to a commit, ensure that there are no dangling refs

**Comment by dlamoris** [comment]
don't you need 1 staging per ref in case the refs point to the same commit? doing a model commit to ref 1 should not change the staging for ref 2

**Comment by dlamoris** [comment]
may be dup of #74
